/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthLogoutRouteImport } from './routes/_auth/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedTutorTutorRouteImport } from './routes/_authenticated/tutor/tutor'
import { Route as AuthenticatedStudentMejoresRouteImport } from './routes/_authenticated/student/mejores'
import { Route as AuthenticatedStudentConfiguracionRouteImport } from './routes/_authenticated/student/configuracion'
import { Route as AuthenticatedStudentCompasRouteImport } from './routes/_authenticated/student/compas'
import { Route as AuthenticatedStudentCalderosRouteImport } from './routes/_authenticated/student/calderos'
import { Route as AuthenticatedTutorCoursesIndexRouteImport } from './routes/_authenticated/tutor/courses/index'
import { Route as AuthenticatedStudentCalderosIndexRouteImport } from './routes/_authenticated/student/calderos/index'
import { Route as AuthenticatedStudentCalderosCourseSlugRouteImport } from './routes/_authenticated/student/calderos/$courseSlug'
import { Route as AuthenticatedTutorCoursesCourseSlugIndexRouteImport } from './routes/_authenticated/tutor/courses/$courseSlug/index'
import { Route as AuthenticatedStudentCalderosCourseSlugIndexRouteImport } from './routes/_authenticated/student/calderos/$courseSlug/index'
import { Route as AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRouteImport } from './routes/_authenticated/tutor/courses/$courseSlug/lesson.$lessonSlug'
import { Route as AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteImport } from './routes/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug'
import { Route as AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRouteImport } from './routes/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug.index'
import { Route as AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRouteImport } from './routes/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug.assessment'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTutorTutorRoute = AuthenticatedTutorTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedStudentMejoresRoute =
  AuthenticatedStudentMejoresRouteImport.update({
    id: '/mejores',
    path: '/mejores',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentConfiguracionRoute =
  AuthenticatedStudentConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentCompasRoute =
  AuthenticatedStudentCompasRouteImport.update({
    id: '/compas',
    path: '/compas',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentCalderosRoute =
  AuthenticatedStudentCalderosRouteImport.update({
    id: '/calderos',
    path: '/calderos',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTutorCoursesIndexRoute =
  AuthenticatedTutorCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedStudentCalderosIndexRoute =
  AuthenticatedStudentCalderosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentCalderosRoute,
  } as any)
const AuthenticatedStudentCalderosCourseSlugRoute =
  AuthenticatedStudentCalderosCourseSlugRouteImport.update({
    id: '/$courseSlug',
    path: '/$courseSlug',
    getParentRoute: () => AuthenticatedStudentCalderosRoute,
  } as any)
const AuthenticatedTutorCoursesCourseSlugIndexRoute =
  AuthenticatedTutorCoursesCourseSlugIndexRouteImport.update({
    id: '/courses/$courseSlug/',
    path: '/courses/$courseSlug/',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedStudentCalderosCourseSlugIndexRoute =
  AuthenticatedStudentCalderosCourseSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentCalderosCourseSlugRoute,
  } as any)
const AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute =
  AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRouteImport.update({
    id: '/courses/$courseSlug/lesson/$lessonSlug',
    path: '/courses/$courseSlug/lesson/$lessonSlug',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute =
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteImport.update({
    id: '/lesson/$lessonSlug',
    path: '/lesson/$lessonSlug',
    getParentRoute: () => AuthenticatedStudentCalderosCourseSlugRoute,
  } as any)
const AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute =
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute,
    } as any,
  )
const AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute =
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRouteImport.update(
    {
      id: '/assessment',
      path: '/assessment',
      getParentRoute: () =>
        AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/student/calderos': typeof AuthenticatedStudentCalderosRouteWithChildren
  '/student/compas': typeof AuthenticatedStudentCompasRoute
  '/student/configuracion': typeof AuthenticatedStudentConfiguracionRoute
  '/student/mejores': typeof AuthenticatedStudentMejoresRoute
  '/tutor/tutor': typeof AuthenticatedTutorTutorRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/student/calderos/$courseSlug': typeof AuthenticatedStudentCalderosCourseSlugRouteWithChildren
  '/student/calderos/': typeof AuthenticatedStudentCalderosIndexRoute
  '/tutor/courses/': typeof AuthenticatedTutorCoursesIndexRoute
  '/student/calderos/$courseSlug/': typeof AuthenticatedStudentCalderosCourseSlugIndexRoute
  '/tutor/courses/$courseSlug/': typeof AuthenticatedTutorCoursesCourseSlugIndexRoute
  '/student/calderos/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteWithChildren
  '/tutor/courses/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute
  '/student/calderos/$courseSlug/lesson/$lessonSlug/assessment': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute
  '/student/calderos/$courseSlug/lesson/$lessonSlug/': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/student/compas': typeof AuthenticatedStudentCompasRoute
  '/student/configuracion': typeof AuthenticatedStudentConfiguracionRoute
  '/student/mejores': typeof AuthenticatedStudentMejoresRoute
  '/tutor/tutor': typeof AuthenticatedTutorTutorRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/student/calderos': typeof AuthenticatedStudentCalderosIndexRoute
  '/tutor/courses': typeof AuthenticatedTutorCoursesIndexRoute
  '/student/calderos/$courseSlug': typeof AuthenticatedStudentCalderosCourseSlugIndexRoute
  '/tutor/courses/$courseSlug': typeof AuthenticatedTutorCoursesCourseSlugIndexRoute
  '/tutor/courses/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute
  '/student/calderos/$courseSlug/lesson/$lessonSlug/assessment': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute
  '/student/calderos/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/_authenticated/student/calderos': typeof AuthenticatedStudentCalderosRouteWithChildren
  '/_authenticated/student/compas': typeof AuthenticatedStudentCompasRoute
  '/_authenticated/student/configuracion': typeof AuthenticatedStudentConfiguracionRoute
  '/_authenticated/student/mejores': typeof AuthenticatedStudentMejoresRoute
  '/_authenticated/tutor/tutor': typeof AuthenticatedTutorTutorRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/student/calderos/$courseSlug': typeof AuthenticatedStudentCalderosCourseSlugRouteWithChildren
  '/_authenticated/student/calderos/': typeof AuthenticatedStudentCalderosIndexRoute
  '/_authenticated/tutor/courses/': typeof AuthenticatedTutorCoursesIndexRoute
  '/_authenticated/student/calderos/$courseSlug/': typeof AuthenticatedStudentCalderosCourseSlugIndexRoute
  '/_authenticated/tutor/courses/$courseSlug/': typeof AuthenticatedTutorCoursesCourseSlugIndexRoute
  '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteWithChildren
  '/_authenticated/tutor/courses/$courseSlug/lesson/$lessonSlug': typeof AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute
  '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/assessment': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute
  '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/': typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/student'
    | '/tutor'
    | '/student/calderos'
    | '/student/compas'
    | '/student/configuracion'
    | '/student/mejores'
    | '/tutor/tutor'
    | '/student/'
    | '/student/calderos/$courseSlug'
    | '/student/calderos/'
    | '/tutor/courses/'
    | '/student/calderos/$courseSlug/'
    | '/tutor/courses/$courseSlug/'
    | '/student/calderos/$courseSlug/lesson/$lessonSlug'
    | '/tutor/courses/$courseSlug/lesson/$lessonSlug'
    | '/student/calderos/$courseSlug/lesson/$lessonSlug/assessment'
    | '/student/calderos/$courseSlug/lesson/$lessonSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/tutor'
    | '/student/compas'
    | '/student/configuracion'
    | '/student/mejores'
    | '/tutor/tutor'
    | '/student'
    | '/student/calderos'
    | '/tutor/courses'
    | '/student/calderos/$courseSlug'
    | '/tutor/courses/$courseSlug'
    | '/tutor/courses/$courseSlug/lesson/$lessonSlug'
    | '/student/calderos/$courseSlug/lesson/$lessonSlug/assessment'
    | '/student/calderos/$courseSlug/lesson/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_authenticated/student'
    | '/_authenticated/tutor'
    | '/_authenticated/student/calderos'
    | '/_authenticated/student/compas'
    | '/_authenticated/student/configuracion'
    | '/_authenticated/student/mejores'
    | '/_authenticated/tutor/tutor'
    | '/_authenticated/student/'
    | '/_authenticated/student/calderos/$courseSlug'
    | '/_authenticated/student/calderos/'
    | '/_authenticated/tutor/courses/'
    | '/_authenticated/student/calderos/$courseSlug/'
    | '/_authenticated/tutor/courses/$courseSlug/'
    | '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug'
    | '/_authenticated/tutor/courses/$courseSlug/lesson/$lessonSlug'
    | '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/assessment'
    | '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/tutor/tutor': {
      id: '/_authenticated/tutor/tutor'
      path: '/tutor'
      fullPath: '/tutor/tutor'
      preLoaderRoute: typeof AuthenticatedTutorTutorRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/student/mejores': {
      id: '/_authenticated/student/mejores'
      path: '/mejores'
      fullPath: '/student/mejores'
      preLoaderRoute: typeof AuthenticatedStudentMejoresRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/configuracion': {
      id: '/_authenticated/student/configuracion'
      path: '/configuracion'
      fullPath: '/student/configuracion'
      preLoaderRoute: typeof AuthenticatedStudentConfiguracionRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/compas': {
      id: '/_authenticated/student/compas'
      path: '/compas'
      fullPath: '/student/compas'
      preLoaderRoute: typeof AuthenticatedStudentCompasRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/calderos': {
      id: '/_authenticated/student/calderos'
      path: '/calderos'
      fullPath: '/student/calderos'
      preLoaderRoute: typeof AuthenticatedStudentCalderosRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/tutor/courses/': {
      id: '/_authenticated/tutor/courses/'
      path: '/courses'
      fullPath: '/tutor/courses/'
      preLoaderRoute: typeof AuthenticatedTutorCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/student/calderos/': {
      id: '/_authenticated/student/calderos/'
      path: '/'
      fullPath: '/student/calderos/'
      preLoaderRoute: typeof AuthenticatedStudentCalderosIndexRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosRoute
    }
    '/_authenticated/student/calderos/$courseSlug': {
      id: '/_authenticated/student/calderos/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/student/calderos/$courseSlug'
      preLoaderRoute: typeof AuthenticatedStudentCalderosCourseSlugRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosRoute
    }
    '/_authenticated/tutor/courses/$courseSlug/': {
      id: '/_authenticated/tutor/courses/$courseSlug/'
      path: '/courses/$courseSlug'
      fullPath: '/tutor/courses/$courseSlug/'
      preLoaderRoute: typeof AuthenticatedTutorCoursesCourseSlugIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/student/calderos/$courseSlug/': {
      id: '/_authenticated/student/calderos/$courseSlug/'
      path: '/'
      fullPath: '/student/calderos/$courseSlug/'
      preLoaderRoute: typeof AuthenticatedStudentCalderosCourseSlugIndexRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosCourseSlugRoute
    }
    '/_authenticated/tutor/courses/$courseSlug/lesson/$lessonSlug': {
      id: '/_authenticated/tutor/courses/$courseSlug/lesson/$lessonSlug'
      path: '/courses/$courseSlug/lesson/$lessonSlug'
      fullPath: '/tutor/courses/$courseSlug/lesson/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug': {
      id: '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug'
      path: '/lesson/$lessonSlug'
      fullPath: '/student/calderos/$courseSlug/lesson/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosCourseSlugRoute
    }
    '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/': {
      id: '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/'
      path: '/'
      fullPath: '/student/calderos/$courseSlug/lesson/$lessonSlug/'
      preLoaderRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute
    }
    '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/assessment': {
      id: '/_authenticated/student/calderos/$courseSlug/lesson/$lessonSlug/assessment'
      path: '/assessment'
      fullPath: '/student/calderos/$courseSlug/lesson/$lessonSlug/assessment'
      preLoaderRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRouteImport
      parentRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteChildren {
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute
}

const AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteChildren: AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteChildren =
  {
    AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute:
      AuthenticatedStudentCalderosCourseSlugLessonLessonSlugAssessmentRoute,
    AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute:
      AuthenticatedStudentCalderosCourseSlugLessonLessonSlugIndexRoute,
  }

const AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteWithChildren =
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute._addFileChildren(
    AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteChildren,
  )

interface AuthenticatedStudentCalderosCourseSlugRouteChildren {
  AuthenticatedStudentCalderosCourseSlugIndexRoute: typeof AuthenticatedStudentCalderosCourseSlugIndexRoute
  AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute: typeof AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteWithChildren
}

const AuthenticatedStudentCalderosCourseSlugRouteChildren: AuthenticatedStudentCalderosCourseSlugRouteChildren =
  {
    AuthenticatedStudentCalderosCourseSlugIndexRoute:
      AuthenticatedStudentCalderosCourseSlugIndexRoute,
    AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRoute:
      AuthenticatedStudentCalderosCourseSlugLessonLessonSlugRouteWithChildren,
  }

const AuthenticatedStudentCalderosCourseSlugRouteWithChildren =
  AuthenticatedStudentCalderosCourseSlugRoute._addFileChildren(
    AuthenticatedStudentCalderosCourseSlugRouteChildren,
  )

interface AuthenticatedStudentCalderosRouteChildren {
  AuthenticatedStudentCalderosCourseSlugRoute: typeof AuthenticatedStudentCalderosCourseSlugRouteWithChildren
  AuthenticatedStudentCalderosIndexRoute: typeof AuthenticatedStudentCalderosIndexRoute
}

const AuthenticatedStudentCalderosRouteChildren: AuthenticatedStudentCalderosRouteChildren =
  {
    AuthenticatedStudentCalderosCourseSlugRoute:
      AuthenticatedStudentCalderosCourseSlugRouteWithChildren,
    AuthenticatedStudentCalderosIndexRoute:
      AuthenticatedStudentCalderosIndexRoute,
  }

const AuthenticatedStudentCalderosRouteWithChildren =
  AuthenticatedStudentCalderosRoute._addFileChildren(
    AuthenticatedStudentCalderosRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentCalderosRoute: typeof AuthenticatedStudentCalderosRouteWithChildren
  AuthenticatedStudentCompasRoute: typeof AuthenticatedStudentCompasRoute
  AuthenticatedStudentConfiguracionRoute: typeof AuthenticatedStudentConfiguracionRoute
  AuthenticatedStudentMejoresRoute: typeof AuthenticatedStudentMejoresRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentCalderosRoute:
    AuthenticatedStudentCalderosRouteWithChildren,
  AuthenticatedStudentCompasRoute: AuthenticatedStudentCompasRoute,
  AuthenticatedStudentConfiguracionRoute:
    AuthenticatedStudentConfiguracionRoute,
  AuthenticatedStudentMejoresRoute: AuthenticatedStudentMejoresRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorTutorRoute: typeof AuthenticatedTutorTutorRoute
  AuthenticatedTutorCoursesIndexRoute: typeof AuthenticatedTutorCoursesIndexRoute
  AuthenticatedTutorCoursesCourseSlugIndexRoute: typeof AuthenticatedTutorCoursesCourseSlugIndexRoute
  AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute: typeof AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorTutorRoute: AuthenticatedTutorTutorRoute,
  AuthenticatedTutorCoursesIndexRoute: AuthenticatedTutorCoursesIndexRoute,
  AuthenticatedTutorCoursesCourseSlugIndexRoute:
    AuthenticatedTutorCoursesCourseSlugIndexRoute,
  AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute:
    AuthenticatedTutorCoursesCourseSlugLessonLessonSlugRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
